#!/bin/csh 

#This script combines VS results into a scores file (extract_all) and a poses file (getposes) to view in chimera

 set d37 = "$DOCK_BASE/src/dock37tools"

 set prefixName = "frags-now-marvin"
 #set prefixName = "leads-now-marvin"
 #set prefixName = "natural-products"

 set mountdir = `pwd`
 echo "mountdir = $mountdir"

 set workdir = "$mountdir/vs_$prefixName" 

 cd $workdir
 
 # ignore bad poses with scores greater than -20.0
 echo $d37/extract_all.py -s -20.0
 $d37/extract_all.py -s -20.0
 
 # top poses for chimera viewdock
 # '-z' flag connects to ZINC for vendor information, 
 # '-l 1000' flag only gets the first 1000 ligands in the file,
 # '-x 2' gets the top 2 poses,
 # '-f ligands.txt' file designates the ligand file to use (generated by extract_all)
 # '-o ligands.1000.mol2' designates the output filename
 $d37/getposes.py -z -l 1000 -x 1 -f extract_all.sort.uniq.txt -o top.1000.mol2  
  
